DATA SEGMENT
    MSG1 DW 10,13,'Bhavish B S$'
    MSG2 DW 10,13,'USN ID: 4NM19CS040$'  
    MSG3 DW 10,13,'SEM 3, BATCH A2$'
    MSG4 DW 10,13,'B.E IN COMPUTER SCIENCE AND ENGINEERING$'    
    MSG5 DW 10,13,'NMAMIT, NITTE$'
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE,DS:DATA
START:
    MOV AX,DATA
    MOV DS,AX
    
    LEA DX,MSG1
    MOV AH,09H
    INT 21H
    
    LEA DX,MSG2
    MOV AH,09H
    INT 21H
    
    LEA DX,MSG3
    MOV AH,09H
    INT 21H

    LEA DX,MSG4
    MOV AH,09H
    INT 21H
            
    LEA DX,MSG5
    MOV AH,09H
    INT 21H
    
    MOV AH,4CH
    INT 21H
    
CODE ENDS   
END START