; FIND THE GCD OF 2 NUMBERS

DATA SEGMENT
    A DW 0018H    ;NUMBER 1
    B DW 0016H    ;NUMBER 2
    TMP DW ?
    GCD DW ? 
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE,DS:DATA
START:
        MOV AX,DATA
        MOV DS,AX 
        
        MOV AX,A    ;AX = 0018H
        MOV BX,B    ;BX = 0016H
        
   CHK: CMP AX,BX   ;COMPARING 2 NUMBERS
        JE BRU      ;CONDIT: FOUND THE ANSWER
        JG S1       ;CONDIT: ANS. NOT FOUND. REDUCE THE LARGER NO. AND TRY AGAIN
        
        MOV TMP,BX  ;MISPLACED NUMBERS, WON'T BE SUITABLE TO CALC. GCD
        MOV BX,AX   ;EXCHANGE THE VALUES OF AX AND BX
        MOV AX,TMP
        
    S1: MOV DX,0000H
        DIV BX
        
        CMP AH,00H
        JE BRU
        
        MOV AL,AH
        MOV AH,00H
        MOV AX,CX
        JMP CHK     ;GO TO CHK TO CHECK WHETHER WE HAVE FOUND THE ANSWER
        
   BRU: MOV GCD,BX   ;STORE THE RESULT TO "GCD"
        
        MOV AH,4CH ;DOS (21H) FUNCTION NUMBER
        INT 21H    ;TERMINATES THE PROGRAM WITH RETURN CODE
    
CODE ENDS   
END START